version: 1.0.{build}
image: Previous Visual Studio 2019
configuration: Debug
platform: x86
build:
  project: game2d.sln
  verbosity: minimal
deploy:
- provider: GitHub
  release: BreakoutGame.exe
  auth_token:
    secure: aOjxIN6QbqcgO16enkFEundxitsOEHCfXdmcM7bmEf8jCRIMy6xJBmTPHfWI0mIi
  draft: true